config/routes.rb
Rails.application.routes.draw do
  # Routes for the Message resource:

  # CREATE
  post("/insert_message", { :controller => "messages", :action => "create" })
          
  # READ
  get("/messages", { :controller => "messages", :action => "index" })
  
  get("/messages/:path_id", { :controller => "messages", :action => "show" })
  
  # UPDATE
  
  post("/modify_message/:path_id", { :controller => "messages", :action => "update" })
  
  # DELETE
  get("/delete_message/:path_id", { :controller => "messages", :action => "destroy" })

  #------------------------------

  # Routes for the Vote resource:

  post("/insert_poll", { :controller => "books", :action => "poll_update" })

  post("/close_poll", { :controller => "books", :action => "poll_close" })

  # CREATE
  post("/insert_vote", { :controller => "votes", :action => "create" })
          
  # READ
  get("/votes", { :controller => "votes", :action => "index" })
  
  # UPDATE
  
  post("/modify_vote/:path_id", { :controller => "votes", :action => "update" })
  
  # DELETE
  get("/delete_vote/:path_id", { :controller => "votes", :action => "destroy" })

  #------------------------------

  # Routes for the Reading resource:

  # CREATE
  post("/insert_reading", { :controller => "readings", :action => "create" })
  
  get("/readings/:path_id", { :controller => "readings", :action => "show" })
  
  # UPDATE
  
  post("/modify_reading/:path_id", { :controller => "readings", :action => "update" })
  
  # DELETE
  get("/delete_reading/:path_id", { :controller => "readings", :action => "destroy" })

  #------------------------------

  # Routes for the Attendance resource:

  # CREATE
  post("/insert_attendance", { :controller => "attendances", :action => "create" })
          
  # READ
  get("/attendances", { :controller => "attendances", :action => "index" })
  
  get("/attendances/:path_id", { :controller => "attendances", :action => "show" })
  
  # UPDATE
  
  post("/modify_attendance/:path_id", { :controller => "attendances", :action => "update" })
  
  # DELETE
  get("/delete_attendance/:path_id", { :controller => "attendances", :action => "destroy" })

  #------------------------------

  # Routes for the Meeting resource:

  # CREATE
  post("/insert_meeting", { :controller => "meetings", :action => "create" })
          
  # READ
  get("/meetings", { :controller => "meetings", :action => "index" })

  get("/meetings/new", { :controller => "meetings", :action => "new" })
  
  get("/meetings/:path_id", { :controller => "meetings", :action => "show" })
  
  # UPDATE
  
  post("/update_meeting/:path_id", { :controller => "meetings", :action => "update" })
  
  # DELETE
  get("/delete_meeting/:path_id", { :controller => "meetings", :action => "destroy" })

  #------------------------------

  # Routes for the Book resource:

  # CREATE
  post("/insert_book", { :controller => "books", :action => "create" })
          
  # READ
  
  get("/books/:path_id", { :controller => "books", :action => "show" })
  
  # UPDATE
  
  post("/modify_book/:path_id", { :controller => "books", :action => "update" })
  
  # DELETE
  get("/delete_book/:path_id", { :controller => "books", :action => "destroy" })

  #------------------------------

  devise_for :members
  get("/members/:path_id", { :controller => "members", :action => "show" })

  get("/members/profile/:path_id", { :controller => "members", :action => "my_profile" })

  get("/members", { :controller => "members", :action => "index" })

  # Defines the root path route ("/")
  root "books#homepage"

end

app/models/meeting.rb
# == Schema Information
#
# Table name: meetings
#
#  id                :integer          not null, primary key
#  attendances_count :integer
#  date              :date
#  notes             :string
#  photos            :string
#  status            :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  book_id           :integer
#
class Meeting < ApplicationRecord
  validates(:date, :book_id, :status, presence: true)
 
  has_many  :attendances, dependent: :destroy
  belongs_to :book_associated, class_name: "Book", foreign_key: "book_id"
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def index
    matching_meetings = Meeting.all

    @list_of_meetings = matching_meetings.order({ :created_at => :desc })

    t = Date.today

    @past_meetings = matching_meetings.where('date < ?', t)

    matching_books = Book.all

    @expired_books = matching_books.where({ :status => "Past Club read" })
    render({ :template => "meetings/index" })

  end

  def show
    the_id = params.fetch("path_id")

    matching_meetings = Meeting.where({ :id => the_id })

    @the_meeting = matching_meetings.at(0)

    matching_attendances = Attendance.where({ :meeting_id => the_id })

    @list_of_attendances = matching_attendances.order({ :created_at => :desc })

    render({ :template => "meetings/show" })
  end

  def new
    matching_meetings = Meeting.all

    t = Date.today

    @list_of_meetings = matching_meetings.order({ :created_at => :desc })

    @future_meetings = matching_meetings.where('date > ?', t)

    @active_meeting = @future_meetings.at(0)

    @next_meeting = @future_meetings.at(1)

    matching_books = Book.all

    @list_of_books = matching_books.order({ :created_at => :desc })

    @potential_books = matching_books.where({ :status => "Potential Club read" })

    @poll_books = matching_books.where({ :status => "Current poll" })

    @chosen_books = matching_books.where({ :status => "Chosen read" })

    matching_votes = Vote.all

    @list_of_votes = matching_votes.order({ :created_at => :desc })

    @votes_count = @poll_books.joins(:votes).group('id').count
    
    @votes_in_order = @votes_count.sort_by { |id, votes| votes }.reverse

    @old_current_book = matching_books.where({ :status => "Chosen read" }).order({ :created_at => :desc }).at(0)

    render({ :template => "meetings/new" })
  end

  def create
    the_meeting = Meeting.new
    the_meeting.date = params.fetch("query_date")
    the_meeting.book_id = params.fetch("query_book_id")
    the_meeting.status = params.fetch("query_status")
    the_meeting.attendances_count = "0"

    if the_meeting.valid?
      the_meeting.save
      redirect_to("/meetings/new", { :notice => "Meeting created successfully." })
    else
      redirect_to("/meetings", { :alert => the_meeting.errors.full_messages.to_sentence })
    end

    t = Date.today
    past_meetings = matching_meetings.where('date < ?', t)
    pas_meetings.update_all.({ :status => "Past meeting" })


  end

  def update
    the_id = params.fetch("path_id")
    @the_meeting = Meeting.where({ :id => the_id }).at(0)

    @the_meeting.date = params.fetch("query_date")
    @the_meeting.book_id = params.fetch("query_book_id")
    @the_meeting.status = params.fetch("query_status")
    @the_meeting.attendances_count = params.fetch("query_attendances_count")
    @the_meeting.notes = params.fetch("query_notes")
    @the_meeting.photos= params.fetch("query_photos")

    if @the_meeting.valid?
      @the_meeting.save
      redirect_to("/meetings/#{@the_meeting.id}", { :notice => "Meeting updated successfully."} )
    else
      redirect_to("/meetings/#{@the_meeting.id}", { :alert => @the_meeting.errors.full_messages.to_sentence })
    end
  end

  def destroy
    the_id = params.fetch("path_id")
    the_meeting = Meeting.where({ :id => the_id }).at(0)

    the_meeting.destroy

    redirect_to("/meetings", { :notice => "Meeting deleted successfully."} )
  end
end

app/views/meetings/index.html.erb
<div>

  &emsp;
  <div>
    <h2>
      Past Book Club meetings
    </h2>
  </div>
</div>


<div>
  <div>
    <table class="table table-hover">
      <thead>
    <tr class="table-active">
        <th scope="col">
          Date
        </th>

        <th scope="col">
          Book discussed
        </th>


        <th scope="col">
          Attendance
        </th>

        <th scope="col">
        </th>
    </tr>
  </thead>
  <tbody>

      <% @past_meetings.each do |a_meeting| %>
      <tr>

        <td>
          <%= a_meeting.date.strftime("%D") %>
        </td>

        <td>
          <a href="/books/<%= a_meeting.book_id %>"><%= a_meeting.book_associated.title %>
        </td>

        <td>
          <%= a_meeting.attendances_count %>
        </td>
        <td>
          <a href="/meetings/<%= a_meeting.id %>">
            Show details
          </a>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>




<div>
  &emsp;
   <h2>
   Past books
   </h2>
 <div>

   <table class="table table-hover">
      <thead>
    <tr class="table-active">
        <th scope="col">
         Title
       </th>

                            <th scope="col">
         Author
       </th>


                            <th scope="col">
         Genre
       </th>


              <th scope="col">
         Status
       </th>



       <th scope="col">
         Readers
       </th>

       <th scope="col">
       </th>
     </tr>
  </thead>
  <tbody>

     <% @expired_books.each do |a_book| %>
     <tr>

       <td>
         <%= a_book.title %>
       </td>

              <td>
         <%= a_book.author %>
       </td>

                     <td>
         <%= a_book.genre %>
       </td>

              <td>
         <% @meetings_of_book = @list_of_meetings.where({ :book_id => a_book.id }).at(0) %>
         
         <% if @meetings_of_book != nil  %> 
         Past Club read
         <% else  %> 
         Not chosen
         <% end %>

         
       </td>

       <td>
         <%= a_book.readers.count %>
       </td>



       <td>
         <a href="/books/<%= a_book.id %>">
           Show details
         </a>
       </td>
     </tr>
     <% end %>
       </tbody>
   </table>
 </div>
</div>

app/views/meetings/new.html.erb
<div style="text-align:left; margin:15px;">
 <div>
 
   <h2>

     Add a new book
   </h2>

   <form action="/insert_book" method="post">
     <div>
       <label for="title_box">
         Title
       </label>
       <input type="text" id="title_box" name="query_title">
     </div>

     <div>
       <label for="author_box">
         Author
       </label>
       <input type="text" id="author_box" name="query_author">
     </div>
    
      <div>
       <label for="genre_box">
         Genre
       </label>
        <select id="genre_box" name="query_genre">
        <option value="Fantasy">Fantasy</option>
        <option value="Science Fiction">Science Fiction</option>
        <option value="Mystery">Mystery</option>
        <option value="Romance">Romance</option>
        <option value="Thriller">Thriller</option>
        <option value="Historical Fiction">Historical Fiction</option>
        <option value="Non-Fiction">Non-Fiction</option>
        <option value="Horror">Horror</option>
        <option value="Adventure">Adventure</option>
        <option value="Biography">Biography</option>
        <option value="Dystopian">Dystopian</option>
        <option value="Comedy">Comedy</option>
        <option value="Drama">Drama</option>
        <option value="Poetry">Poetry</option>
        </select>
        </div>
     <div>
       <label for="pages_box">
         Number of pages
       </label>
       <input type="number" id="pages_box" name="query_number_of_pages">
     </div>

     <div>
       <label for="cover_box">
       Book cover image URL
       </label>
       <input type="text" id="cover_box" name="query_cover_url">
     </div>
       <input type="hidden" id="status_box" name="query_status" value="Potential Club read">
     <button class="btn btn-dark">
       Create book
     </button>
   </form>
   
 </div>
</div>
<hr>

<div style="text-align:left; margin:15px;">
   <h2>
     Create new poll
   </h2>

<form action="/insert_poll" method="post">
      <div>
        <label for="date_box">
          Meeting
        </label>
        <select id="date_box" name="query_date">
        <% @future_meetings.each do |a_book| %>
        <option value="<%= a_book.id %>"><%= a_book.date.strftime("%D") %></option>
        <% end %>
       </select>
      </div>
      
    <div class="form-group">
      <label for="book_id_box" class="form-label mt-4">Potential books</label>
      <select multiple="" id="book_id_box" name="query_book_ids">
          <% @potential_books.each do |a_book| %>
        <option value="<%= a_book.id %>"><%= a_book.title %></option>
        <% end %>
      </select>
    </div>
      <button class="btn btn-dark">
        Add to poll
      </button>
    </form>


<hr>
  <div>

    <h2>
      Create new Book Club meeting
    </h2>

<form action="/insert_meeting" method="post">
      <div>
        <label for="date_box">
          Date
        </label>

        <input type="date" id="date_box" name="query_date">
      </div>

      <div>
        <label for="book_id_box">
          Most-voted books (only udpates after poll is closed)
        </label></div>
<div>
        <select id="book_id_box" name="query_book_id">
        <% @chosen_books.each do |a_book| %>
        <option value="<%= a_book.id %>"><%= a_book.title %></option>
        <% end %>

       </select>
      </div>

      <div>
        <label for="status_box">
          Status
        </label>

        <select id="status_box" name="query_status">
        <option value="Future meeting">Future meeting</option>
        </select>
      </div>
<div style="text-align:left; margin:15px;">
      <button class="btn btn-dark">
        Create meeting
      </button></div>
    </form>
  </div>
</div>
<hr>


<div style="text-align:left; margin:15px;">
   <h2>
     Current poll
   </h2>

   <% if @poll_books.at(0) != nil %>
  
<h7> Votes for the meeting on <%= @next_meeting.date.strftime("%D") %></h7>

<center>
<%= pie_chart @poll_books.joins(:votes).group('title').count, library: { title: 'Votes per Book' }, legend: "left" %></center>

   <% if @votes_in_order.at(0) != nil %>

<form action="/close_poll" method="post">
      
    <div class="form-group">
      <input type="hidden" id="chosen_book_box" name="query_book_ids" value="<%= @votes_in_order.at(0).at(0) %>">
      <button class="btn btn-dark">
        Close poll
      </button>
    </form>
</div>
<% else  %>
<div> Still waiting for members to vote.
<% end %>

<% else  %>
<div> Last poll chose <%= @old_current_book.title %> as the next Booth Book Club read. There are no open polls right now. </div>
<% end %>
</div>

app/views/meetings/show.html.erb
<div>
  <div>
    <h1>
      <%= @the_meeting.date.strftime("%B") %> Meeting details
    </h1>

    <div>
      <div>
        <a href="/meetings">
          Go back
        </a>
      </div>
 <% if current_member != nil %>
 <% if current_member.admin_status == true %>
      <div>
        <a href="/delete_meeting/<%= @the_meeting.id %>">
          Delete meeting
        </a>
      </div>
    </div>

    <% else %>
<div> </div>
     <% end %>
       <% else %>
       <div></div>

     <% end %>
    <dl>
      <dt>
        Date
      </dt>
      <dd>
        <%= @the_meeting.date.strftime("%D") %>
      </dd>

      <dt>
        Book
      </dt>
      <dd>
        <%= @the_meeting.book_associated.title %>
      </dd>

            <dt>
        Meeting notes
      </dt>
      <dd>
        <%= @the_meeting.notes %>
      </dd>

      <dt>
        Total attendance count
      </dt>
      <dd>
        <%= @the_meeting.attendances_count %>
      </dd>

      <dt>
        Members who checked-in
      </dt>
              <% @the_meeting.attendances.each do |an_attendant| %>
      <dd>
        <%= an_attendant.member.username %>
      </dd>
<% end %>
      <dt>
        Official photo
      </dt>
      <dd>
        <%= @the_meeting.photos %>
      </dd>
    </dl>
  </div>
</div>

 <% if current_member != nil %>
 <% if current_member.admin_status == true %>

 <hr>
<div>
  <div>
    <h3>
      (Co-chairs only)Edit meeting
    </h3>

<form action="/update_meeting" method="post">
<input type="hidden" id="book_box" name="query_book_id" value="<% @the_meeting.book_id %>">
<input type="hidden" id="date_box" name="query_date" value="<% @the_meeting.date %>">
           <div>
       <label for="attendance_box">
      Attendance count
       </label>
       <input type="number" id="attendance_box" name="query_attendances_count">
     </div>

       <div>
       <label for="notes_box">
         Notes
       </label>
       <input type="text" id="notes_box" name="query_notes">
     </div>
       <div>
       <label for="photos_box">
         Photo URL
       </label>
       <input type="text" id="photos_box" name="query_photos">
     </div>

      <div>
        <label for="status_box">
          Status
        </label>

        <select id="status_box" name="query_status">
        <option value="Current meeting">Current meeting</option>
        <option value="Past meeting">Past meeting</option>
        </select>
      </div>
            <button>
        Update meeting
      </button>
      </form>
      <% else %>
<div> </div>
     <% end %>
       <% else %>
       <div></div>

     <% end %>